### ISSUE TITLE
sharing apps from phone to desktop

### ISSUE THREAD

**Issue by drdozer** [vikoadi/indicator-kdeconnect#19]
Hi - I think kdeconnector is great. It would be even greater if I could share apps from the phone onto a window on my dekstop. Either whatever is on the phone screen, or super-awesome if I could grab any one of the running apps and project/pin it in its own desktop panel. That way when my phone is paired, I could attach the chat app and other things so that I don't have to keep on switching between interfaces.

**Comment by vikoadi** [comment]
Hello drdozer,
I only maintain the Ubuntu's indicator part of kdeconnect, please write your feature request (and praise) to the awesome guys of KDEConnect here https://bugs.kde.org/enter_bug.cgi?product=kdeconnect

**Comment by drdozer** [comment]
Cheers :) Sorry, must have got lost in a twisty maze of projects, all alike.
