### ISSUE TITLE
Indicator doesn't show up.

### ISSUE THREAD

**Issue by cybre** [vikoadi/indicator-kdeconnect#2]
I can see the `indicator-kdeconnect` process in the process list but the indicator fails to load.
I am using elementary OS Freya beta1 and the version of `kdeconnect` is `0.5.2.1-0ubuntu0.1`

**This is the output:**
*\* (indicator-kdeconnect:12264): WARNING *_: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-tVnM0nHQZx: Connection refused
*_ Message: KDEConnectManager.vala:29: retrying to find KDE Connect DBus service
*\* Message: KDEConnectManager.vala:29: retrying to find KDE Connect DBus service
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
kdeconnect(12267)/kdeconnect_kded Daemon::Daemon: Starting KdeConnect daemon
*\* Message: KDEConnectManager.vala:29: retrying to find KDE Connect DBus service﻿

**Comment by vikoadi** [comment]
A notification icon will only show up after KDE Connect application started in connected android.
