### ISSUE TITLE
Redundant cli tool?

### ISSUE THREAD

**Issue by albertvaka** [vikoadi/indicator-kdeconnect#4]
I've seen that you made your own "kdeconnect-send" CLI tool, and I think you could use "kdeconnect-cli" instead. It should be installed with kdeconnect by default, and among other things it allows you to send files using the --share option.

**Comment by vikoadi** [comment]
unlike kdeconnect-cli, kdeconnect-send doesn't need device id to be supplied first, instead it will show all your available device and ask user to which device file/url is to be sent (so its not entirely cli). 
i don't know how its done in dolphin, but in nautilus/pantheon-files I will only need to call "kdeconnect-send _filename_" and doesn't need to prepopulate the devices.
Thats why i wrote this tool,

**Comment by albertvaka** [comment]
Oh, sorry for the confusion then. I'm trying to install pantheon on top of Arch to be able to test your code, but I haven't succeeded yet.
