### ISSUE TITLE
Broken on newer distros - Mint 18

### ISSUE THREAD

**Issue by x8BitRain** [vikoadi/indicator-kdeconnect#43]
error: cannot connect to KDE Connect DBus service

OS: Mint 18 "Sarah"

tolong update bro, distro baru nggak bisa dipakai :(

WORKAROUND: Remove your installation of the indicator and kdeconnect and install kdeconnect-plasma instead!

> apt install kdeconnect-plasma

Reinstall the indicator via PPA

> sudo add-apt-repository ppa:vikoadi/ppa
> sudo apt update
> sudo apt install kdeconnect

and start do "indicator-kdeconnect" in the terminal to start it again, it should work on ubuntu 16 and mint 18!

**Comment by NiklasMerz** [comment]
I got the same error After upgrading to Mint 18 Base Ubuntu 16.04

**Comment by edouard-lopez** [comment]
I was hoping to install it just now. Which version did you tried?

**Comment by edouard-lopez** [comment]
## Environment

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 18 Sarah
Release:        18
Codename:       sarah
```

## Packages Version

**dbus**

```
$ apt show dbus
Version: 1.10.6-1ubuntu3
```

**indicator-kdeconnect**

```
$ apt show indicator-kdeconnect
Version: 0.1-0~41~ubuntu16.04.1
```

**kdeconnect**

```
apt show kdeconnect
Version: 0.8-0ubuntu5
```

## Output

```
$ indicator-kdeconnect
** Message: KDEConnectManager.vala:29: retrying to find KDE Connect DBus service
** Message: KDEConnectManager.vala:29: retrying to find KDE Connect DBus service
** Message: KDEConnectManager.vala:29: retrying to find KDE Connect DBus service
** Message: KDEConnectManager.vala:29: retrying to find KDE Connect DBus service
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
fish: “indicator-kdeconnect” terminated by signal SIGSEGV (Address boundary error)
```

## Related
- #38: [indicator kde-connect not working](https://github.com/vikoadi/indicator-kdeconnect/issues/38) 
- #42: [Does not work on elementary OS 0.4 beta 1](https://github.com/vikoadi/indicator-kdeconnect/issues/42)

**Comment by x8BitRain** [comment]
I tried the one from the PPA and I tried building it from the Source, neither worked, and both showed the same error, it's also on a fresh install of Mint 18.

**Comment by edouard-lopez** [comment]
@x8BitRain last commit on indicator-kdeconnect date from Dec 22, 2014…

**Comment by x8BitRain** [comment]
It worked on 17.3, also the point of me making this issue to get the guy to fix it.

**Comment by edouard-lopez** [comment]
Linux Mint [`17.3` is based on Ubuntu `14.04` while `18` is based on `16.04`](https://www.wikiwand.com/en/List_of_Linux_Mint_releases#/Release_history).

**Comment by x8BitRain** [comment]
I KNOW, I made the issue to tell the author that the fuckin thing doesn't work on 16.04 based systems.

**Comment by t0rx309** [comment]
I've spent hours trying to get it to work. I was trying different repos and all kind of configurations, I can tell what finally helped me to start kdeconnect. I might work for you as well. Uninstall all kdeconnect packages: indicator-kdeconnect kdeconnect kdeconnect-plasma . Now get deb from this site 
http://www.makeuseof.com/tag/kde-connect-sync-android-linux/ install it and then install indicator-kdeconnect again. Hopefully this will work for you...

**Comment by rodneyrod** [comment]
Has anyone here checked out the KF5 branch to see if that works with the libraries included with 16.04?

**Comment by Oneiriac** [comment]
On Fedora 24 (Gnome 3.20.4) the only way I've gotten this indicator to work is by building from this fork: https://github.com/Bajoja/indicator-kdeconnect . The KF5 branch didn't work, and neither did Albert Vaka's fork.

I was already paired using the KDE Connect Settings app (kcmshell5 kcm_kdeconnect) so I didn't test whether you can pair from the indicator. However, everything works fine (Battery percentage, Device Reachable and Trusted, Send file, Find my phone) except Browse device; it opens the correct directory (~/.config/kdeconnect/[device ID]/kdeconnect_sftp/[device ID]), but this directory is empty.

**Comment by ghost** [comment]
i havent followed Bajoja's fork yet, but when Will Vikoadi update this for the newer distros? or atleast check Bajoja's code to see if everything is ok??

anyone?

**Comment by rndmh3ro** [comment]
@Beast141 the last commit from  vikoadi is almost 2 years old, so you probably won't get any updates here. Better switch to bajojas fork now, its working for me on Arch Linux.

**Comment by varlesh** [comment]
**PPA Ubuntu 16.04 / Linux Mint 18 / elementary OS Loki**:

```
sudo add-apt-repository ppa:varlesh-l/indicator-kdeconnect
sudo apt update
sudo apt install kdeconnect indicator-kdeconnect
```

**Comment by samandiriel** [comment]
I can confirm that varlesh's ppa version is working on my fresh Mint 18.1 + MATE install (x64 AMD)

Yayyyyyyy!

**Comment by ghost** [comment]
@varlesh thank you so much, its working now i can see the indicator!  However there is a plugin in the phone app that says Send SMS, send text messages from your desktop, it is ticked and enabled - but im assuming this feature is not yet available in kdeconnect on Ubuntu? cause i cant find the option to view/send text messages.

any news about this? thanks

**Comment by ob1kenobi** [comment]
YES. It worked fine on Peppermint  7

**Comment by KennyLauchlan** [comment]
@varlesh 
Thnks very much, solved an headache here, kdeconnect is a must have for me in the Linux world
I do wonder, can you shed some light on why the 'browse device' shows an empty folder? and how to fix/view device files

**Comment by ghost** [comment]
@KennyLauchlan 
Vikoadi's ppa and Varlesh's ppa is no longer updated as often.. The new official ppa is this one:

sudo add-apt-repository ppa:webupd8team/indicator-kdeconnect
sudo apt update
sudo apt install kdeconnect indicator-kdeconnect

from
https://github.com/Bajoja/indicator-kdeconnect
