### ISSUE TITLE
Resolvido. Mostrar ícone kdeconnect na área de notificação (Show kdeconnect icon in systray)

### ISSUE THREAD

**Issue by dognew** [vikoadi/indicator-kdeconnect#49]
Solução:
- Baixar pacote do [github](https://github.com/Bajoja/indicator-kdeconnect)
- Descompacte o pacote
- Acesse a pasta indicator-kdeconnect-master/data/icons/
- Copie todas as pastas para /usr/share/icons
- Reinicie o computador
- Pronto!

Obs.: Utilizo Linuxmint 18

**Comment by b4j4** [comment]
@dognew Não é mais facil você instalar e usar esse repositorio do que apenas copiar esses icones.

**Comment by dognew** [comment]
@Bajoja

Muitas pessoas tiveram esse probleminha. Compartilhei a solução.

**Comment by b4j4** [comment]
@dognew a solução para um problema que já tem 2 anos e nunca foi resolvido neh, portanto este fork aqui é um problemão.
