### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by endlesslight0** [vikoadi/indicator-kdeconnect#6]
Which ports does kdeconnect use? WiFi router that my smartphone is connected is behind the network that my PC is connected. If I knew the ports, I could setup port forwarding on the WiFi router.

**Comment by vikoadi** [comment]
Please ask at KDE Connect mailing list
https://mail.kde.org/mailman/listinfo/kdeconnect

**Comment by albertvaka** [comment]
The ports you have to open are the range 1714-1764, in both TCP and UPD.
